### ISSUE TITLE
Server Console Hangs After Saving World

### ISSUE THREAD

**Issue by randormi** [CmdrJane/Fabric-restart#2]
When having Fabric-restart in the mods folder and telling the server to restart (via op) or shutting off the server via console, the console hangs at

`[Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved`

I have to go into my task manager (htop) in order to kill the process for the server in order to open the server back up.

**Comment by CmdrJane** [comment]
Please provide list of all mods as well as minecraft version and mod version

**Comment by randormi** [comment]
Minecraft Version 1.17.1

Mods (using Fabric 0.11.6)

Additional Additions v2.1.3
Animal Feeding Trough v1.0.2
Appleskin Forge v1.17.1-2.1.0
Architectury v2.5.27
Backslot v1.2.0
Balm v1.3.0+0
Bclib v.0.3.1
Better End v.0.11.0-pre
Better Dropped Items v1.3.0
Better Dungeons v1.0.1
Better Mineshafts v1.0.1
Better Safe Bed v1.4
Bewitchment v1.17-6
Bountiful v1.0.0
Caelus v0.0.17
Cardinal Components API v3.1.1
Carrier v1.8.0
Cloth API v2.0.54
Cloth Config v5.0.38
Clumps v7.0.6
Cosmetic Armor v1.1.0
Couplings v1.5.1
Customizable Elytra v1.5.1
Drink Beer v2.1
Dual Riders v1.0.5
Elytra Trinket v2.0.1
Enchantment Descriptions v4.0.1
Fabric API v0.40.1
Fabric Language Kotlin v1.6.4 + Kotlin v1.5.30
Falling Tree v2.13.0
Fast Furnace v3.0
Fishing Real v1.1.0
Flan v1.6.2
Impersonate v2.3.3
InvView v1.4.6
Kambrik v1.1.0
Lapis Reserve v1.0.8
LuckPerms v5.3.67
Midnight Lib v0.2.4
Mod Menu v2.0.10
Mo' Structures v1.2.1
Nether Chest v2.0
Netherite Horse Armor v1.3.1
New Caves v2.2
Pal v1.3.0
Particle Rain v1.5.0
Patchouli v1.17-54
Pehkui v2.4.0
Polymorph v0.0.13
Repurposed Structures v.2.3.3
Right Click Harvest v.1.4.0
Secret Rooms v1.0.0
Sit v1.17.1-13
Somnus v0.0.14
Spyglass Zoom v1.0.1
Stoneholm v1.3
The Graveyard v1.4
Trinkets v3.0.4
Waystones v8.1.1+0
Wolves with Armor v1.6.1
Wraith Alloy Forgery v2.0.3
XP Storage v1.4.2
Yungs API v16

**Comment by CmdrJane** [comment]
Okay im gonna check that a bit later, as temporary solution you can enable shutdown watcher in cfg
